name: ubuntu-make
version: 'master'
summary: Setup your development environment on ubuntu easily
description: |
  Ubuntu Make provides a set of functionality to setup,
  maintain and personalize your developer environment easily. It will handle
  all dependencies, even those which aren't in Ubuntu itself, and install
  latest versions of the desired and recommended tools.
  .
  This is the latest master from ubuntu make, freshly built from
  https://github.com/ubuntu/ubuntu-make. It may contain even unreleased
  features!
grade: stable
confinement: classic

apps:
  umake:
    command: bin/umake
    completer: umake-completion

parts:
  patches:
    source: patches
    plugin: dump
    prime:
        - -*.diff
  umake-completion:
    plugin: dump
    source: snap
    stage:
      - umake-completion
  umake-wrapper:
    source: snap/
    plugin: dump
    organize:
      umake-wrapper: bin/umake-wrapper
  umake:
    source: .
    plugin: python
    organize:
      lib/python3/dist-packages/umake: lib/python3.5/site-packages/umake
    #requirements: requirements.txt
    after: [patches]
    install: |
      patch $SNAPCRAFT_PART_INSTALL/usr/lib/python3.5/ctypes/__init__.py $SNAPCRAFT_STAGE/ctypes_init.diff
    build-packages:
      - gettext
      - python3-apt
      - python3-argcomplete
      - python3-bs4
      - python3-gi
      - python3-gnupg
      - python3-setuptools
      - python3-nose
      - python3-nose-cov
      - python3-nose-json
      - python3-pep8
      - python3-pexpect
      - python3-progressbar
      - python3-yaml
      - python3-requests
      - python3-xdg
      - dbus-x11
      - fakeroot
      - help2man
    stage-packages:
      - python3-apt
      - python3-argcomplete
      - python3-bs4
      - python3-gi
      - python3-gnupg
      - python3-progressbar
      - python3-yaml
      - python3-requests
      - python3-xdg
  umake-completion:
    plugin: dump
    source: snap
    stage:
      - umake-completion
#  apt:
#      source: https://github.com/Debian/apt
#      source-type: git
#      source-tag: 1.2.19
#      source-depth: 1
#      plugin: autotools
#      prepare: |
#          make startup
#      build: |
#          mkdir apt-build
#          cd apt-build
#          ../configure
#          make
#      install: |
#          cd apt-build
#          install -d $SNAPCRAFT_PART_INSTALL/apt
#          cp -r bin/methods/* $SNAPCRAFT_PART_INSTALL/apt/
#          cp -r bin/methods/* $SNAPCRAFT_PART_INSTALL/apt/
#          install bin/apt-key $SNAPCRAFT_PART_INSTALL/apt/
#          install bin/apt-mark $SNAPCRAFT_PART_INSTALL/apt/
#          install bin/apt-internal-solver $SNAPCRAFT_PART_INSTALL/apt/
#          install bin/apt-helper $SNAPCRAFT_PART_INSTALL/apt/
#          install -d $SNAPCRAFT_PART_INSTALL/usr/lib
#          install bin/libapt-inst.so.2.0.0 $SNAPCRAFT_PART_INSTALL/usr/lib/
#          install bin/libapt-pkg.so $SNAPCRAFT_PART_INSTALL/usr/lib/
#          install bin/libapt-pkg-5.0-0.symver $SNAPCRAFT_PART_INSTALL/usr/lib/
#          install bin/libapt-private.so $SNAPCRAFT_PART_INSTALL/usr/lib/
#          install bin/libapt-private-0.0-0.symver $SNAPCRAFT_PART_INSTALL/usr/lib/
#          install bin/libapt-private.so.0.0.0 $SNAPCRAFT_PART_INSTALL/usr/lib/
#          install bin/libapt-inst.so.2.0 $SNAPCRAFT_PART_INSTALL/usr/lib/
#          install bin/libapt-inst.so $SNAPCRAFT_PART_INSTALL/usr/lib/
#          install bin/libapt-pkg.so.5.0 $SNAPCRAFT_PART_INSTALL/usr/lib/
#          install bin/libapt-inst-2.0-0.symver $SNAPCRAFT_PART_INSTALL/usr/lib/
#          install bin/libapt-pkg.so.5.0.0 $SNAPCRAFT_PART_INSTALL/usr/lib/
#          install bin/libapt-private.so.0.0 $SNAPCRAFT_PART_INSTALL/usr/lib/
#          install -d $SNAPCRAFT_PART_INSTALL/usr/include
#          cp -r include/* $SNAPCRAFT_PART_INSTALL/usr/include/
#      prime:
#          - -usr/include
#      build-packages:
#          - gettext
#          - libbz2-dev
#          - libcurl4-gnutls-dev
#          - libdb-dev
#          - liblz4-dev
#          - liblzma-dev
#          - zlib1g-dev
