name: ubuntu-make
version: 'master'
summary: Setup your development environment on ubuntu easily
description: |
  Ubuntu Make provides a set of functionality to setup,
  maintain and personalize your developer environment easily. It will handle
  all dependencies, even those which aren't in Ubuntu itself, and install
  latest versions of the desired and recommended tools.
  .
  This is the latest master from ubuntu make, freshly built from
  https://github.com/ubuntu/ubuntu-make. It may contain even unreleased
  features!
grade: stable
confinement: classic

apps:
  umake:
    command: bin/umake-wrapper
    completer: umake-completion

parts:
  patches:
    source: patches
    plugin: dump
    prime:
      - -*.diff
  umake-completion:
    plugin: dump
    source: snap
    stage:
      - umake-completion
  umake-wrapper:
    plugin: dump
    source: snap/
    organize:
      umake-wrapper: bin/umake-wrapper
  umake:
    source: .
    plugin: python
    organize:
      lib/python3/dist-packages/umake: lib/python3.5/site-packages/umake
    build-packages:
      - gettext
      - python3-apt
      - python3-argcomplete
      - python3-bs4
      - python3-gi
      - python3-gnupg
      - python3-setuptools
      - python3-nose
      - python3-nose-cov
      - python3-nose-json
      - python3-pep8
      - python3-pexpect
      - python3-progressbar
      - python3-yaml
      - python3-requests
      - python3-xdg
      - dbus-x11
      - fakeroot
      - help2man
    stage-packages:
      - python3-apt
      - python3-argcomplete
      - python3-bs4
      - python3-gi
      - python3-gnupg
      - python3-progressbar
      - python3-yaml
      - python3-requests
      - python3-xdg
    override-build: |
        snapcraftctl build
        patch $SNAPCRAFT_PART_INSTALL/usr/lib/python3.5/ctypes/__init__.py $SNAPCRAFT_STAGE/ctypes_init.diff
    override-prime: |
        # This is the last step, let's now compile all our pyc files.
        snapcraftctl prime
        ./usr/bin/python3 -m compileall .
    after: [patches]
